# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: FortifyOnDemandStatic@9
  inputs:
    FortifyProjects: 
    FodConnection: 'name'
    ReleaseOptions: '0'
    ReleaseId: 150673
    EntitlementSelection: '1'
    EntitlementPreference: '2'
    OverrideScanSettings: '2'
    InProgressScanActionType: '2'
    RemediationScanPreference: '2'
    BuildType: 'none'
    PolicyFailAction: '1'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
